=== DKid-LOL/HocTap/json-xml/buoi6_de1/students.dtd
<!ELEMENT Students (Student+)>
<!ATTLIST Students
          xmlns CDATA #IMPLIED
          xmlns:xsi CDATA #IMPLIED>
<!ELEMENT Student (ID, FullName, BirthDate, Major)>
<!ELEMENT ID (#PCDATA)>
<!ELEMENT FullName (#PCDATA)>
<!ELEMENT BirthDate (#PCDATA)>
<!ELEMENT Major (#PCDATA)>

=== DKid-LOL/HocTap/json-xml/buoi6_de1/students.xml
<?xml version="1.0" encoding="UTF-8"?>
<!DOCTYPE Students SYSTEM "students.dtd">
<Students xmlns="http://example.com/students"
          xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance">
          
    <Student>
        <ID>1</ID>
        <FullName>PHA</FullName>
        <BirthDate>2001-05-15</BirthDate>
        <Major>Code</Major>
    </Student>

    <Student>
        <ID>2</ID>
        <FullName>PHB</FullName>
        <BirthDate>2001-09-20</BirthDate>
        <Major>Code</Major>
    </Student>

</Students>
